name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        TIMESTAMP: ${{ github.event.head_commit.timestamp }}
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t surajk00/myplugin:${{ env.TIMESTAMP }} .
        docker push surajk00/myplugin:${{ env.TIMESTAMP }}
