name: Build and push the Docker image

on:
  push:
    branches:
      - main
      - build_action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set timestamp as environment variable
      run: echo "TAG=$(date +%Y-%m-%d-%H%M%S)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:ansahmohammad
        context: .
        file: ./Dockerfile
        push: true
        tags: surajk00/myplugin:${{ env.TAG }}
