name: Docker Image CI

on:
  push:
    branches:
      - main
      - build_action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: surajk00/myplugin:2024-02-09-122911
          load: false
          no-cache: false
          pull: false
          github-token: ${{ secrets.DOCKER_HUB_TOKEN }}
