name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        TIMESTAMP: ${{ github.event.head_commit.timestamp }}
      run: |
       TIMESTAMP=$(date +%Y-%m-%dT%H-%M-%S%z)
       docker buildx build --platform linux/amd64,linux/arm64 -t surajk00/myplugin:$TIMESTAMP .
       docker push surajk00/myplugin:$TIMESTAMP
      
